### PR TITLE
Change package names for Opensuse (fixes #221)

### LINKED ISSUE #221: Build fails on openSUSE Tumbleweed
Building the package on my openSUSE Tumbleweed machine fails.

```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH Sandybridge)
  LAPACK: libopenblas_openmp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

julia> Pkg.build("Cairo")
INFO: Building Cairo
INFO: Attempting to create directory /home/patrik/.julia/v0.6/Cairo/deps/downloads                             
INFO: Directory /home/patrik/.julia/v0.6/Cairo/deps/downloads already exists                                   
INFO: Downloading file http://ftp.gnome.org/pub/GNOME/sources/pango/1.32/pango-1.32.6.tar.xz                   
INFO: Done downloading file http://ftp.gnome.org/pub/GNOME/sources/pango/1.32/pango-1.32.6.tar.xz              
INFO: Attempting to create directory /home/patrik/.julia/v0.6/Cairo/deps/src                                   
INFO: Directory /home/patrik/.julia/v0.6/Cairo/deps/src already exists                                         
INFO: Attempting to create directory /home/patrik/.julia/v0.6/Cairo/deps                                       
INFO: Directory /home/patrik/.julia/v0.6/Cairo/deps already exists                                             
INFO: Path /home/patrik/.julia/v0.6/Cairo/deps/src/pango-1.32.6 already exists                                 
INFO: Attempting to create directory /home/patrik/.julia/v0.6/Cairo/deps/builds/pango                          
INFO: Directory /home/patrik/.julia/v0.6/Cairo/deps/builds/pango already exists                                
INFO: Changing directory to /home/patrik/.julia/v0.6/Cairo/deps/builds/pango                                   
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for native Win32... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for c++... c++
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking dependency style of c++... gcc3
checking for sysconf... yes
checking for getpagesize... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for unistd.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/x86_64-suse-linux/bin/ld
checking if the linker (/usr/x86_64-suse-linux/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-suse-linux/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... c++ -E
checking for ld used by c++... /usr/x86_64-suse-linux/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the c++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for c++ option to produce PIC... -fPIC -DPIC
checking if c++ PIC flag -fPIC -DPIC works... yes
checking if c++ static flag -static works... no
checking if c++ supports -c -o file.o... yes
checking if c++ supports -c -o file.o... (cached) yes
checking whether the c++ linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
configure: creating ./config.lt
config.lt: creating libtool
checking for some Win32 platform... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for HARFBUZZ... no
no
checking for CoreText availability... no
checking for CAIRO... yes
checking which cairo font backends could be used... none
configure: Disabling cairo support
configure: error: *** Could not enable any backends.
*** Must have at least one backend to build Pango.
===============================================[ ERROR: Cairo ]================================================

LoadError: failed process: Process(setenv(`/home/patrik/.julia/v0.6/Cairo/deps/src/pango-1.32.6/configure --prefix=/home/patrik/.julia/v0.6/Cairo/deps/usr`,String["PATH=/home/patrik/.julia/v0.6/Cairo/deps/usr/bin:/home/patrik/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin", "CPU=x86_64", "JRE_HOME=/usr/lib64/jvm/jre", "FROM_HEADER=", "G_FILENAME_ENCODING=@locale,UTF-8,ISO-8859-15,CP1252", "GS_LIB=/home/patrik/.fonts", "KONSOLE_DBUS_SESSION=/Sessions/1", "XSESSION_IS_UP=yes", "XNLSPATH=/usr/share/X11/nls", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "KONSOLE_PROFILE_NAME=", "MANPATH=/usr/local/man:/usr/share/man", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_DESKTOP=KDE", "XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB", "JAVA_ROOT=/usr/lib64/jvm/jre", "XDG_SESSION_TYPE=x11", "PROFILEREAD=true", "QT_IM_MODULE=xim", "USER=patrik", "LESSCLOSE=lessclose.sh %s %s", "XDG_CONFIG_DIRS=/etc/xdg", "JAVA_HOME=/usr/lib64/jvm/jre", "LESS=-M -I -R", "SSH_ASKPASS=/usr/lib/ssh/ssh-askpass", "LESSOPEN=lessopen.sh %s", "XDG_DATA_DIRS=/home/patrik/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "CONFIG_SITE=/usr/share/site/x86_64-unknown-linux-gnu", "SHELL=/bin/bash", "COLORFGBG=15;0", "XDG_SEAT=seat0", "XAUTHORITY=/tmp/xauth-1000-_0", "ALSA_CONFIG_PATH=/etc/alsa-pulse.conf", "GTK_MODULES=canberra-gtk-module", "GTK_IM_MODULE=cedilla", "LESS_ADVANCED_PREPROCESSOR=no", "SESSION_MANAGER=local/T430.local:@/tmp/.ICE-unix/2004,unix/T430.local:/tmp/.ICE-unix/2004", "QT_SYSTEM_DIR=/usr/share/desktop-data", "XMODIFIERS=@im=local", "GPG_TTY=kein Terminal", "XCURSOR_THEME=breeze_cursors", "HOME=/home/patrik", "TERM=xterm-256color", "COLORTERM=truecolor", "HOSTNAME=T430", "SDL_AUDIODRIVER=pulse", "HISTSIZE=1000", "LESSKEY=/etc/lesskey.bin", "MINICOM=-c on", "KONSOLE_DBUS_WINDOW=/Windows/1", "XDG_CURRENT_DESKTOP=KDE", "XAUTHLOCALHOSTNAME=T430", "OSTYPE=linux", "HOST=T430", "LANG=de_DE.UTF-8", "WINDOWMANAGER=/usr/bin/startkde", "LOGNAME=patrik", "SHLVL=1", "XDG_RUNTIME_DIR=/run/user/1000", "DESKTOP_SESSION=/usr/share/xsessions/plasma5", "MACHTYPE=x86_64-suse-linux", "KDE_SESSION_UID=1000", "PROFILEHOME=", "PAGER=less", "_=/usr/lib64/libexec/kf5/start_kdeinit_wrapper", "G_BROKEN_FILENAMES=1", "PWD=/home/patrik", "CSHEDIT=emacs", "DISPLAY=:0", "QT_AUTO_SCREEN_SCALE_FACTOR=0", "XDG_SESSION_CLASS=user", "QEMU_AUDIO_DRV=pa", "LANGUAGE=de:en_US:en_GB", "GTK_RC_FILES=/etc/gtk/gtkrc:/home/patrik/.gtkrc:/home/patrik/.config/gtkrc", "KONSOLE_DBUS_SERVICE=:1.129", "MAIL=/var/spool/mail/patrik", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1", "CPPFLAGS= -I/home/patrik/.julia/v0.6/Cairo/deps/usr/include", "WINDOWID=67108870", "XDG_VTNR=7", "LDFLAGS= -L/home/patrik/.julia/v0.6/Cairo/deps/usr/lib -Wl,-rpath -Wl,/home/patrik/.julia/v0.6/Cairo/deps/usr/lib", "KDE_FULL_SESSION=true", "XDG_SESSION_ID=2", "GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/patrik/.gtkrc-2.0:/home/patrik/.config/gtkrc-2.0", "PYTHONSTARTUP=/etc/pythonstart", "MORE=-sl", "PKG_CONFIG_PATH=/home/patrik/.julia/v0.6/Cairo/deps/usr/lib/pkgconfig", "AUDIODRIVER=pulseaudio", "QT_IM_SWITCHER=imsw-multi", "SHELL_SESSION_ID=ff9735c528c642baaa974acf1bab8708", "JAVA_BINDIR=/usr/lib64/jvm/jre/bin", "HOSTTYPE=x86_64", "KDE_SESSION_VERSION=5", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
while loading /home/patrik/.julia/v0.6/Cairo/deps/build.jl, in expression starting on line 165

===============================================================================================================

===============================================[ BUILD ERRORS ]================================================

WARNING: Cairo had build errors.

 - packages with build errors remain installed in /home/patrik/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Cairo")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================

julia> using BinDeps

julia> BinDeps.debug("Cairo")
INFO: Reading build script...
The package declares 1 dependencies.
 - Library Group "cairo"
     - Library "png" (not applicable to this system)
     - Library "pixman" (not applicable to this system)
     - Library "ffi" (not applicable to this system)
     - Library "gettext"
        - Satisfied by:
          - BinDeps.Zypper package gettext at /usr/lib64/preloadable_libintl.so
          - BinDeps.Zypper package gettext at /usr/lib64/libgettextpo.so
          - Autotools Build at /home/patrik/.julia/v0.6/Cairo/deps/usr/lib64/preloadable_libintl.so
          - Autotools Build at /home/patrik/.julia/v0.6/Cairo/deps/usr/lib64/libgettextpo.so
        - Providers:
          - BinDeps.AptGet package gettext (can't provide)
          - BinDeps.Yum package gettext-libs (can't provide)
          - BinDeps.Zypper package gettext
          - Autotools Build
     - Library "gobject"
        - Satisfied by:
          - Autotools Build at /home/patrik/.julia/v0.6/Cairo/deps/usr/lib64/libgobject-2.0.so
          - Autotools Build at /home/patrik/.julia/v0.6/Cairo/deps/usr/lib64/libgobject-2.0.so.0
          - System Paths at /usr/bin/../lib64/libgobject-2.0.so
        - Providers:
          - BinDeps.AptGet package libglib2.0-0 (can't provide)
          - BinDeps.Yum package glib2 (can't provide)
          - BinDeps.Zypper package libglib-2.0 (can't provide)
          - Autotools Build
     - Library "freetype" (not applicable to this system)
     - Library "fontconfig" (not applicable to this system)
     - Library "cairo"
        - Satisfied by:
          - BinDeps.Zypper package libcairo at /usr/lib64/libcairo.so
          - BinDeps.Zypper package libcairo at /usr/lib64/libcairo.so.2
          - Autotools Build at /home/patrik/.julia/v0.6/Cairo/deps/usr/lib64/libcairo.so
          - Autotools Build at /home/patrik/.julia/v0.6/Cairo/deps/usr/lib64/libcairo.so.2
        - Providers:
          - BinDeps.AptGet package libcairo2 (can't provide)
          - BinDeps.Yum package cairo (can't provide)
          - BinDeps.Zypper package libcairo
          - Autotools Build
     - Library "pango"
        - Satisfied by:
          - System Paths at /usr/lib64/libpango-1.0.so.0
        - Providers:
          - BinDeps.AptGet package libpango1.0-0 (can't provide)
          - BinDeps.Yum package pango (can't provide)
          - BinDeps.Zypper package libpango-1.0 (can't provide)
          - Autotools Build
     - Library "pangocairo"
        - Satisfied by:
          - System Paths at /usr/lib64/libpangocairo-1.0.so.0
        - Providers:
          - BinDeps.AptGet package libpango1.0-0 (can't provide)
          - BinDeps.Yum package pango (can't provide)
          - BinDeps.Zypper package libpango-1.0 (can't provide)
          - Autotools Build
     - Library "zlib" (not applicable to this system)
```

### PR DESCRIPTION
**Pull request by Kryohi**

### CODE REVIEW

**Comment by tkelman** [comment]
Have these changed in all actively used versions of opensuse since @colbec added them in #129?

**Comment by Kryohi** [comment]
I tried searching for the old names in https://software.opensuse.org/search and found nothing opensuse-related, using the "all distributions" option.
Not sure this is the 100% correct way to do it though...

**Comment by lobingera** [comment]
I'll merge this right now. And i'm planning to tag after i did some local testing - trying to run an openSuSE in a virtualbox.

**Comment by lobingera** [comment]
@Kryohi I'm running openSuSE tubleweed in a vbox and the first dependency gettext is getting installed, but then not regocognized. Any comments?

**Comment by colbec** [comment]
Not sure how I can help here, but willing to test. I have the released version of julia 0.6  on openSUSE Leap 42.3 but gave up using it due to persistent problems with ImageView producing errors related to GLib-GObject-CRITICAL. In my julia Cairo deps I have cairo-1.12.6 ,gettext-0.18.2, glib-2.34.3 and pango-1.32.6. Also from Yast I have a gettext-runtime installed.

**Comment by lobingera** [comment]
@Kryohi @colbec I just rechecked, yast reports gettext-runtime installed. When i run Pkg.build("Cairo") (on a new opensuse installation) i get this:
snapshot24

**Comment by colbec** [comment]
I'm using julia 0.6 precompiled binary; when I build Cairo it is silent, so I removed Cairo (including cache) and added back:
```
julia> Pkg.rm("Cairo")
INFO: Package Cairo is not installed

julia> Pkg.add("Cairo")
INFO: Cloning cache of Cairo from https://github.com/JuliaGraphics/Cairo.jl.git
INFO: Installing Cairo v0.5.1
INFO: Building Cairo
INFO: Package database updated

julia> Pkg.build("Cairo")
INFO: Building Cairo

julia> 

```
So openSUSE is not finding a source package on my machine. I tried adding in a package `gettext-tools` but this did not make any difference.
One of the complicating factors on openSUSE to bear in mind is that for some reason unknown to me the developers insist on providing a default package `zypper-aptitude` which contains a truncated version of `apt-get` which can confuse routines that depend on the presence of `apt-get` to discover the flavour of Linux present. But clearly in your case if it is installed the detection can pass that hurdle.

**Comment by Kryohi** [comment]
@lobingera I also just tried to completely remove Cairo and did a Pkg.clone followed by the build and even Pkg.test, and got no errors or warnings.
gettext-runtime and gettext-tools were already installed though.
Also, I never saw the warning you have about libcholmod, maybe it was installed as a dependency of something else. Have you tried installing that library from zypper?

**Comment by colbec** [comment]
@Kryohi - good idea about the Pkg.test, this raises the issue I see with ImageView. I have used TkAgg and GTK as backend for matplotlib, which I understand can be important, may I ask which you are using?
```
julia> Pkg.test("Cairo")
INFO: Testing Cairo

(process:6495): GLib-GObject-CRITICAL **: /home/colin/.julia/v0.6/Cairo/deps/src/glib-2.34.3/gobject/gtype.c:2720: You forgot to call g_type_init()

(process:6495): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed

(process:6495): GLib-GObject-CRITICAL **: /home/colin/.julia/v0.6/Cairo/deps/src/glib-2.34.3/gobject/gtype.c:2720: You forgot to call g_type_init()

(process:6495): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed

(process:6495): GLib-GObject-CRITICAL **: /home/colin/.julia/v0.6/Cairo/deps/src/glib-2.34.3/gobject/gtype.c:2720: You forgot to call g_type_init()

(process:6495): GLib-GObject-CRITICAL **: /home/colin/.julia/v0.6/Cairo/deps/src/glib-2.34.3/gobject/gtype.c:2720: You forgot to call g_type_init()

```

**Pull request merged**
