### PR TITLE
Create CompatHelper.yml

### PR DESCRIPTION
**Pull request by timholy**
https://github.com/bcbi/CompatHelper.jl

### CODE REVIEW

**Comment by giordano** [comment]
Can you please retrigger the drone jobs that failed on 32-bit ARM?  It should be fixed now.

**Comment by timholy** [comment]
I don't think I can, but perhaps @lobingera?

**Comment by timholy** [comment]
Actually, let's try a close/open cycle.

**Comment by lobingera** [comment]
@timholy @giordano 

I have lost track, is this needed?

**Comment by giordano** [comment]
It's not _needed_, but it helps keeping the compat bounds in `Project.toml` up-to-date: a GitHub actions scheduled every day will open a pull request, if necessary, to update them.  In this way you don't need to manually go through each dependency and check whether there are new releases.

**Comment by lobingera** [comment]
Merged.

**Pull request merged**
