### PR TITLE
Return `status_t` from `write_to_png`

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
The aim here would be to be able to debug the test failure in https://travis-ci.org/JuliaGizmos/GtkReactive.jl/jobs/622293709?utm_medium=notification&utm_source=github_status, which only happens on Travis.

**Comment by timholy** [comment]
Bump

**Comment by lobingera** [comment]
Meaning? I thought you're juliagraphics member, so you can merge as you like

**Comment by timholy** [comment]
I can, I just wanted to make sure you didn't disapprove.

**Pull request merged**
