### PR TITLE
Fix from source builds for Julia version < 1.0

### PR DESCRIPTION
**Pull request by tknopp**
@tkelman: Sorry for being too quick. Could you please review, merge this one and initiate a release if this fixed the issue with the from source builds.

### CODE REVIEW

**Comment by tkelman** [comment]
The Windows SimpleBuild can be removed, that's not so useful. The unix one is important.

**Comment by tknopp** [comment]
@tkelman: I have now a version where the Source builds should also work on 1.0. CI is passing. I just had do disable the SimpleBuild on 1.0. Please merge if you are satisfied.

**Comment by tkelman** [comment]
Is that replace syntax available in the Compat version matching the require lower bound?

**Comment by tknopp** [comment]
certainly not. Should I bump to the most recent one (1.0.1)?

**Comment by tkelman** [comment]
no, it was 0.43 https://github.com/JuliaLang/Compat.jl/commit/e450796c0c3603feb7a991bc9e6b7fee2712006b so that's fine

**Pull request merged**
