### PR TITLE
WIP: test gcc dll replacement on appveyor

### PR DESCRIPTION
**Pull request by tkelman**
not sure if this will work, but this may be a way to deal with the win32 issue

### CODE REVIEW

**Comment by lobingera** [comment]
@tkelman Do you think this can be included in mainstream WinRPM soon?

**Comment by tkelman** [comment]
it's a bit risky since the opensuse repo can change at any time, if anything breaks it may result in julia not starting correctly. maybe we could do it only on 32 bit?

**Comment by lobingera** [comment]
@tkelman 
> maybe we could do it only on 32 bit?

yes. 

Can you explain what error/failure you're working around? In my own quest to see why the 32bit fails it looked like the library is installed, but never recognized by julia

**Comment by tkelman** [comment]
The short version is the opensuse build service upgraded to gcc 7 a few months ago, but the Windows Julia binaries are still built (cross-compiled from cygwin on the buildbots) using gcc 5. Evidently there are a few new functions in libgcc in gcc 7 that get used by cairo, but the libgcc that Julia includes does not have.

**Comment by lobingera** [comment]
@tkelman Would you recommend to merge this, now?

**Comment by tkelman** [comment]
Not really, not in this exact form. Could maybe start doing this over in WinRPM's build script but only on 32 bit (since it introduces a risk of upstream changes from opensuse breaking Julia installs unpredictably).

I'm no longer actively doing Julia development, so addressing this issue should probably be undertaken by someone else who regularly uses and tests things on Windows. I don't think there's anyone who fits that description at the moment, at least in terms of active people with commit access to base Julia. Maybe BinDeps2 will have a fully working Windows cross-compilation story eventually.

**Comment by lobingera** [comment]
BinDep2 development already started?

**Comment by ararslan** [comment]
> BinDeps2 development already started?

https://github.com/JuliaPackaging/BinDeps2.jl

**Comment by giordano** [comment]
This can probably be closed now, I guess

**Pull request closed without merging**
