### PR TITLE
Try fixing homebrew issue

### PR DESCRIPTION
**Pull request by tknopp**
just a test to look at travis

### CODE REVIEW

**Comment by tknopp** [comment]
Hm, it fixes the issue in on 0.6 but not 0.7

**Comment by tknopp** [comment]
@staticfloat: I am trying to circumvent the Homebrew issue
```
ERROR: LoadError: Provider Homebrew.HB failed to satisfy dependency pangocairo
```
which seem so be fixed by 
```
using Homebrew
Homebrew.brew(`reinstall fontconfig`)
Pkg.build("Cairo")
```
Do you know why this works on 0.6 but not 0.7 (see travis logs)

**Comment by tknopp** [comment]
there is a timing issue going on, where a global variable is overwritten. That at least my guess. I cannot reproduce this on Mac but on linux.

**Comment by staticfloat** [comment]
Hmmm, it's not obvious to me why the provider is being marked as failing to provide the libraries.  It would be helpful to see `otool -L <path to cairo.dylib>` as well as any other libraries that are not being satisfied.

**Comment by tknopp** [comment]
like this?:
```
	/Users/knopp/.julia/packages/Homebrew/l8kUw/deps/usr/opt/cairo/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.12.0)
	/Users/knopp/.julia/packages/Homebrew/l8kUw/deps/usr/opt/pixman/lib/libpixman-1.0.dylib (compatibility version 35.0.0, current version 35.0.0)
	/Users/knopp/.julia/packages/Homebrew/l8kUw/deps/usr/opt/fontconfig/lib/libfontconfig.1.dylib (compatibility version 12.0.0, current version 12.1.0)
	/Users/knopp/.julia/packages/Homebrew/l8kUw/deps/usr/opt/freetype/lib/libfreetype.6.dylib (compatibility version 22.0.0, current version 22.0.0)
	/Users/knopp/.julia/packages/Homebrew/l8kUw/deps/usr/opt/libpng/lib/libpng16.16.dylib (compatibility version 51.0.0, current version 51.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1450.16.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1129.5.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by tknopp** [comment]
note that this is after the reinstall trick

**Comment by staticfloat** [comment]
I see.  I'm not sure that your PR is actually running the reinstall chunk.  Can you check?  Perhaps passing `;verbose = true` to the `brew()` invocation.

**Comment by tknopp** [comment]
yes, but I am confused. Isn't https://github.com/staticfloat/homebrew-juliadeps/pull/131 intended to solve the root problem or is it worth pushing my workaround here?

**Comment by tknopp** [comment]
Ah and note that the paths I showed you were from my local build and not from the branch I am triggering here.

**Comment by tknopp** [comment]
Last interesting thing for you. After the first install (where fontconfig 2.12.6 was installed) I had 
```
julia> Homebrew.list()
12-element Array{Homebrew.BrewPkg,1}:
 cairo: 1.14.12    
 fontconfig: 2.13.0
 freetype: 2.9.1   
 fribidi: 1.0.5    
 gettext: 0.19.8.1 
 glib: 2.56.1      
 harfbuzz: 1.8.7   
 libffi: 3.2.1     
 libpng: 1.6.35    
 pango: 1.42.3     
 pcre: 8.42        
 pixman: 0.34.0_1  
```
isn't that strange?

**Comment by staticfloat** [comment]
Sorry, what is strange?  I'm going to need you to point it out to me.  Is it the fact that fontconfig 2.13.0 is installed?

**Comment by tknopp** [comment]
Yes, so what I have done was do remove my Homebrew dir and make a fresh Cairo.build (locally). The I saw:
```
│ ==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.6.high_sierra.bottle.tar.gz
│ Already downloaded: /Users/knopp/Library/Caches/Homebrew.jl/fontconfig-2.12.6.high_sierra.bottle.tar.gz
│ ==> Pouring fontconfig-2.12.6.high_sierra.bottle.tar.gz
│ ==> Regenerating font cache, this may take a while
```
which implies to be that version 2.12.6 is installed. But the command `Homebrew.list()` reported 2.13.0. That seems inconsistent.

**Comment by tknopp** [comment]
(I have now put a try/catch around `@BinDeps.install` on this branch, lets see how this works)

**Comment by NHDaly** [comment]
@tknopp, i would not at all be surprised if there are two separate issues, the one I'm fixing for 0.6, and a different issue occurring on 0.7. Thanks for digging in to this though! :)

I found it helpful when debugging to just manually try to load the library and see why it's complaining, like so:
```julia
 # This specific error should be fixed by your experimental patch
julia0.6> h = Libdl.dlopen("/Users/daly/.julia/v0.6/Homebrew/deps/usr/lib/libpangocairo-1.0.dylib", Libdl.RTLD_LAZY)
ERROR: could not load library "/Users/daly/.julia/v0.6/Homebrew/deps/usr/lib/libpangocairo-1.0.dylib"
dlopen(/Users/daly/.julia/v0.6/Homebrew/deps/usr/lib/libpangocairo-1.0.dylib, 1): Library not loaded: /Users/daly/.julia/v0.6/Homebrew/deps/usr/opt/fontconfig/lib/libfontconfig.1.dylib
  Referenced from: /Users/daly/.julia/v0.6/Homebrew/deps/usr/lib/libpangocairo-1.0.dylib
  Reason: Incompatible library version: libpangocairo-1.0.dylib requires version 13.0.0 or later, but libfontconfig.1.dylib provides version 12.0.0
Stacktrace:
 [1] dlopen(::String, ::UInt32) at ./libdl.jl:97
```

Maybe that will help you as well when debugging

**Pull request closed without merging**
