### PR TITLE
Fix Homebrew issues on 0.7 and 1.0

### PR DESCRIPTION
**Pull request by tknopp**
thanks to @affans
https://github.com/JuliaGraphics/Cairo.jl/issues/230#issuecomment-414886635

### CODE REVIEW

**Comment by tknopp** [comment]
This makes me so happy. Appveyor failure is some download error. That passed before I modified travis.

**Comment by affans** [comment]
Glad i could help. I needed all of this for `vegalite` plotting.

**Comment by tkelman** [comment]
This should be fixed at the homebrew recipe level. This is like fixing a missing dependency by manually calling Pkg.add instead of adding it to REQUIRE where it belongs

**Comment by tknopp** [comment]
Yes that is clear. It just needs someone with homebrew knowledge (i.e. not me) to do this. @staticfloat maybe.

**Comment by lobingera** [comment]
@tkelman That's why it's called 'Fix', not 'Solution'...

**Comment by tknopp** [comment]
This discussion leads to nowhere. I find it pretty unsatisfying that the people putting energy into this project are blamed for their work. We don't need to justify ourself to someone who does not use Julia anymore. 

@timholy: I would really like to get support from you in this matter. We got travis all green with this patch and terms like `messy hack workaround` are in my opinion not appropriate here (although I have to admit not being a native speaker).

**Comment by tkelman** [comment]
The problem is more or less here. https://github.com/Homebrew/homebrew-core/blob/83dda4fe2614ad89c3d9715ce0a17f3f580874bf/Formula/harfbuzz.rb#L25

graphite2 is listed as a "recommended" dependency of harfbuzz by homebrew, but the binaries of harfbuzz they're distributing are built linked to graphite2. If you download homebrew's harfbuzz bottles directly and look at the dylibs with otool you should be able to verify this. Either homebrew should be building bottles without linking against recommended dependencies, or the dependencies that are linked against should be handled as full dependencies when installing bottles. If the brew cli already implements this logic for recommended dependencies, then the bug may be in Homebrew.jl's treatment of them.

**Comment by lobingera** [comment]
>  If you download homebrew's harfbuzz bottles directly and look at the dylibs with otool you should be able to verify this.

Can i do this on Linux?

**Comment by tkelman** [comment]
Possibly with ObjectFile.jl? Check what the mac build image for BinaryBuilder uses for otool-like functionality when inspecting linkages. Otherwise it's usually violating the mac sdk's eula to use it on non-apple hardware, annoyingly. http://www.newosxbook.com/tools/jtool.html might be a workable alternative

**Comment by lobingera** [comment]
I see. Still the responsibility to do this correctly is with the homebrew-core formular people? btw: Why are other brew users are not seeing these problems?

**Comment by tkelman** [comment]
I'm not sure what brew's behavior would be in a totally clean environment if you do `brew install harfbuzz` - if it installs graphite2, then Homebrew.jl and the brew cli apparently differ in behavior on recommended dependencies.

**Comment by lobingera** [comment]
@tkelman I borrowed a Macbook and otools shows me on the libharfbuzz.dylib (download from bottle) a dependency on graphite. The jtool thing isn't compiling on linux

**Comment by tkelman** [comment]
And does brew install harfbuzz in a clean environment pull in graphite2? If so, then Homebrew.jl isn't replicating brew's behavior accurately enough.
________________________________

**Comment by lobingera** [comment]
I couldn't run brew on the other computer. Maybe via travis.

**Comment by lobingera** [comment]
@tkelman Can you explain, what 'wrong' effects on a julia installation could happen if graphite2 is installed manually?

**Comment by tkelman** [comment]
This should not be released as-is, it's an incorrect fix and masking a bigger problem that should be fixed directly - either Homebrew.jl isn't handling recommended dependencies correctly, in which case this isn't the only package that will see incorrect behavior, or the homebrew bottle itself was built wrong. It is a bit unfortunate that it requires debugging on a mac to identify which it is. Hopefully someone who's hitting the issue can assist with that.

The workaround here incorrectly treats graphite2 as if it was manually requested to be installed by the user, rather than only being installed as a dependency of something else.

**Comment by timholy** [comment]
@tkelman, can you just fix it yourself? The key concern is that it appears none of us know how. While I have a very superficial understanding of the issues here, I agree with your sentiments; nevertheless, I assure you we are not going to freeze progress in Cairo.jl indefinitely (see #254) just for a fix that would be "more ideal."

At a minimum, since Cairo isn't the fundamental problem it would be good to report our concerns in the appropriate location. I'm not the right person to do that.

**Comment by tkelman** [comment]
Without a mac, no I can't determine the correct fix either. I'm fine releasing 254 without this. Some of the individuals who are hitting the issue that this works around should be able to assist in identifying the actual problem. Really anyone with a mac.

**Comment by timholy** [comment]
OK, let's revert this. There are lots of mac users in #230, let's continue the conversation there. @tkelman if you can coach one of them through what they should be trying, that would be a huge help.

**Comment by tkelman** [comment]
The longer this gets left in place, the more users are going to end up in an incorrect state that will interfere with future debugging and installation, given the wrong treatment of the graphite2 dependency here. The "at a minimum" has not been done, and there's shockingly little indication of anyone caring about fixing this the permanent, correct, non-harmful, upstream way. A little bit of iteration (on a mac) through what's happening on 0.6 and 0.7 to identify whether it's Homebrew.jl or the homebrew packaging of cairo/harfbuzz at fault here is all that's necessary. If this incorrect band-aid gets left here indefinitely, is anyone actually going to look into the real problem?

**Pull request merged**
