### PR TITLE
Provide macro @libcall to simplify ccall's

### PR DESCRIPTION
**Pull request by emmt**
A macro is provided to automatically use the correct library based on the prefix of the function. This makes the code a bit more readable and less prone to errors.  The macro `Cairo.@libcall` can be used in other packages to simplify calling a Cairo/Pango function.

### CODE REVIEW

**Comment by lobingera** [comment]
"and less prone to errors" - which errors?

**Comment by emmt** [comment]
Well when the code is more clear and easier to read, I think that it less likely to make it wrong. I did not meant that that there were errors ;-)

**Comment by asinghvi17** [comment]
This now exists in Base's `@ccall` macro.

**Comment by ViralBShah** [comment]
Agree this should be done with `@ccall`

**Pull request closed without merging**
